server:
  port: 8763

spring:
  application:
    name: SearchService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hbase:
  host: 172.23.253.80
  table:
    name: test
  columnfamily:
    fiveAve: info
