server:
  port: 8763

spring:
  application:
    name: SearchService
  datasource:
    url: jdbc:mysql://172.23.253.80:3306/stock_portrait
    username: root
    password: Hadoopc102*
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hbase:
  host: 172.23.253.80

